#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec  7 14:29:07 2022

@author: deo010
"""

#%% Folder destination

print("""
      
      For section of the script, stay in the folder destination containing the .sf files (usually the source name folder).
      
      """)


#%% Importing modules

import os

#%% Creating time files

def extracttime(data,dm):
    os.system('grep {} {}.candidates > ATEMP.candidates'.format(dm,data))
    return "awk '{print $3}' ATEMP.candidates > ATEMPS.cands"

#%% Get archive for each file

def archive(time,dm,name,data,count):
    # output archive files
    return 'dspsr -S {} -T 1.5 -U 12000 -b 1500 -c 1.5 -D {} -O {}{}ARCH {}'.format(time,dm,name,count,data)

#%% Archive function

def DSPSR(data,name,dm):
      
    # create count to loop over all candidates
    count = 1
      
    # get DM rows and times
    os.system(extracttime(data,dm))
    times = open("ATEMPS.cands")
      
    # select time 0.5s before identified burst
    for time in times:
        t = float(time) - 0.5
        os.system(archive('{}'.format(t),dm,name,data,count))
        count += 1
      
    # remove temporary ATEMP* files
    os.system('rm -f ATEMP*')
    
    # make a directory to store .ar files, unless it already exists (if rerunning code)
    os.system('mkdir -pv ARCHIVEs')
    
    # move all .ar files to the ARCHIVEs/ folder
    os.system("mv *ARCH.ar ARCHIVEs/")

#%% Example code for one source

filename = 't170526_143519.sf'
DSPSR(data='{}'.format(filename),name = '{}'.format(filename),dm='820.00')

#%% Looping over all candidates


for filename in os.listdir():
    if filename.endswith(".sf"):
        print(" ")
        print('Now working on: {}'.format(filename))
        DSPSR(data='{}'.format(filename),name = '{}'.format(filename),dm='820.00')
        
#%% Folder destination

print("""
      
      For section of the script, go to the ARCHIVEs/ folder destination containing the .ar files.
      
      """)

        
#%% Looping over all archives

for filename in os.listdir():
    if filename.endswith(".ar"):
        print(filename)
        os.system('pav -d -GTp {}'.format(filename))

#%% Folder destination

print("""
      
      For section of the script, go to the folder destination containing the .sf files (usually the source name folder).
      
      """)

#%% Loop over all files to extract only your chosen value DM candidates, in this case DM = 820.00

for filename in os.listdir():
    if filename.endswith(".sf"):
        print(" ")
        print('Now working on: {}'.format(filename))
        os.system('grep 820.00 {}.candidates > {}_cuts.candidates'.format(filename,filename))
        
    
