#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec  7 14:29:07 2022

@author: deo010
"""

#%% Folder destination

print("""
      
      For section of the script, stay in the folder destination containing the .sf files (usually the source name folder).
      
      """)


#%% Importing modules

import os

#%% Creating time files

def extracttime(data,dm):
    os.system('grep {} {}.candidates > ATEMP.candidates'.format(dm,data))
    return "awk '{print $3}' ATEMP.candidates > ATEMPS.cands"

#%% Get archive for each file

def archive(time,dm,name,data,count):
    # output archive files
    return 'dspsr -S {} -T 1.5 -U 12000 -b 1500 -c 1.5 -D {} -O {}{}ARCH {}'.format(time,dm,name,count,data)

#%% Archive function

def DSPSR(data,name,dm):
    
    count = 1
    # get DM rows and times
    os.system(extracttime(data,dm))
    
    times = open("ATEMPS.cands")
    
    for time in times:
        t = float(time) - 0.5
        os.system(archive('{}'.format(t),dm,name,data,count))
        count += 1
        
    os.system('rm -f ATEMP*')
    
    os.system('mkdir -pv ARCHIVEs')
    
    os.system("mv *ARCH.ar ARCHIVEs/")
    
    # get archive
    #os.system(archive(time,dm,name,data)) 

#%%

filename = 't211001_084100.sf'
DSPSR(data='{}'.format(filename),name = '{}'.format(filename),dm='700.00')

#%%
filename = 't201026_074244.sfARCH.ar'
os.system('pav -d -GTp {}'.format(filename))

#%%
filename = 't170526_143519.sf'
os.system('grep 820.00 {}.candidates > {}_cuts.candidates'.format(filename,filename))

#%% Looping over all candidates

for filename in os.listdir():
    if filename.endswith(".sf"):
        print(" ")
        print('Now working on: {}'.format(filename))
        DSPSR(data='{}'.format(filename),name = '{}'.format(filename),dm='700.00')
        #name = os.system('filename:0:4')
        #print(name)
        
#%% Folder destination

print("""
      
      For section of the script, go to the ARCHIVEs/ folder destination containing the .ar files.
      
      """)

        
#%% Looping over all archives
#extracttime(, '700.00','AAATEST3')

for filename in os.listdir():
    if filename.endswith(".ar"):
        print(filename)
        os.system('pav -d -GTp {}'.format(filename))

#%%

os.system('pav -d -GTp t180212_014009.sfARCH.ar')

#%% Folder destination

print("""
      
      For section of the script, go to the folder destination containing the .sf files (usually the source name folder).
      
      """)


#%% Loop over all files to extract only your chosen value DM candidates

for filename in os.listdir():
    if filename.endswith(".sf"):
        print(" ")
        print('Now working on: {}'.format(filename))
        os.system('grep 700.00 {}.candidates > {}_cuts.candidates'.format(filename,filename))
        
#%%
count = 1
for i in range(10):
    count += 1
    print(count)
    
    
    
    
    
    
    
    
    



        