#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec  5 10:49:04 2022

@author: deo010
"""

#%% Folder destination

print("""
      
      For this script, stay in the folder destination containing the .sf files (usually the source name folder).
      
      """)


# %% Importing modules

import os

# %% Rfifinds
def rfifind(data,time,name):
    # Parameters 
    # data:
    # time:
     return "rfifind -psrfits -zerodm -time {} -noweights -noscales -noclip -o {} {}".format(time,name,data)

# %% De-dispersion

def prepsubband(name,chan,lodm,dmstep,numdms,data):
    # Parameters
    # chan:
    # lodm
    # dmstepbackspace
    # numdms
    # data
    return 'prepsubband -mask {}_rfifind.mask -noscales -nsub 64 -ignorechan {} -lodm {} -dmstep {} -numdms {} -zerodm -o {} {}'.format(name,chan,lodm,dmstep,numdms,name, data)
    
# %% Single pulse search

def single_pulse(threshold, ms, name):
    return 'single_pulse_search.py -t {} -m {} {}_DM*.dat'.format(threshold,ms,name)

# %% Large function

# os.system("rfifind -flags -o out t150418_180959.sf")

def PRESTO(data,name,time,chan,lodm,dmstep,numdms,threshold,ms):
    
    # rfifinds
    os.system(rfifind(data,time,name))
    
    # ghostview
    # os.system("gv {}_rfifind.ps".format(name))
    
    # prepping subbands
    os.system(prepsubband(name,chan,lodm,dmstep,numdms,data))
    
    # single search
    os.system(single_pulse(threshold,ms,name))
    
    # ghostview
    # os.system ("gv {}_singlepulse.ps".format(name))
    
    # search for candidates
    os.system('touch {}.candidates'.format(data))
    os.system('cat *.singlepulse >> {}.candidates'.format(data))
    
    os.system("mkdir F_{}/".format(data))
    os.system("mv {}* F_{}/".format(name,data))

# %% Source 1

PRESTO(data = 't201026_074244.sf',name = 't201026_074244.sfTEST',time = '2.0',chan = '0', lodm = '780', dmstep = '10', numdms = '10', threshold = '30', ms = '0.05')


#%% Looping
for filename in os.listdir():
    if filename.endswith(".sf"):
        print(" ")
        print("Now working on: {}".format(filename))
        PRESTO(data = '{}'.format(filename),name = '{}TEST'.format(filename),time = '2.0',chan = '0', lodm = '650', dmstep = '10', numdms = '10', threshold = '30', ms = '0.05')
#os.system('touch ALL.Candidates')
#os.system('cat *.candidates >> ALL.Candidates')

    #%%
print("hello")

#%%
os.system('gv F_t201026_074244.sf/*_singlepulse.ps') 


















































